/*
  Test project
  Generated by ArduDeck from a visual flow.
  - Light Sensor -> A0
  - LED -> D9
*/

// --- Pins ---
const int lightPin = A0;
const int ledPin = 9;

void setup() {
  pinMode(ledPin, OUTPUT);
}

void loop() {
  int lightValue = analogRead(lightPin);

  // Light Sensor is less than 300
  if (lightValue < 300) {
    digitalWrite(ledPin, HIGH);
  } else {
    digitalWrite(ledPin, LOW);
  }

  delay(50);
}
