export type TokenClass = 'txt' | 'com' | 'pre' | 'kw' | 'num' | 'str' | 'fn' | 'type';

export interface Token {
  text: string;
  cls: TokenClass;
}

const KEYWORDS = new Set([
  'if',
  'else',
  'for',
  'while',
  'return',
  'const',
  'void',
  'unsigned',
  'byte',
  'bool',
  'true',
  'false',
  'HIGH',
  'LOW',
  'OUTPUT',
  'INPUT',
  'INPUT_PULLUP',
]);

const TYPES = new Set(['int', 'long', 'float', 'double', 'char', 'Servo', 'String']);

const BUILTINS = new Set([
  'pinMode',
  'digitalWrite',
  'digitalRead',
  'analogRead',
  'analogWrite',
  'tone',
  'noTone',
  'pulseIn',
  'delay',
  'delayMicroseconds',
  'millis',
  'micros',
]);

const IDENT_START = /[A-Za-z_]/;
const IDENT_PART = /[A-Za-z0-9_]/;
const DIGIT = /[0-9]/;

/**
 * Small, dependency-free C++ highlighter. The code we show is generated by
 * ArduDeck itself, so the token set stays small and predictable.
 */
export function tokenizeCode(code: string): Token[][] {
  const lines = code.split('\n');
  const result: Token[][] = [];
  let inBlockComment = false;

  for (const line of lines) {
    const tokens: Token[] = [];
    let index = 0;

    const push = (text: string, cls: TokenClass): void => {
      const previous = tokens[tokens.length - 1];
      if (previous && previous.cls === cls) {
        tokens[tokens.length - 1] = { text: previous.text + text, cls };
      } else {
        tokens.push({ text, cls });
      }
    };

    while (index < line.length) {
      if (inBlockComment) {
        const end = line.indexOf('*/', index);
        if (end === -1) {
          push(line.slice(index), 'com');
          index = line.length;
        } else {
          push(line.slice(index, end + 2), 'com');
          index = end + 2;
          inBlockComment = false;
        }
        continue;
      }

      const rest = line.slice(index);

      if (rest.startsWith('//')) {
        push(rest, 'com');
        break;
      }
      if (rest.startsWith('/*')) {
        inBlockComment = true;
        continue;
      }
      if (rest.startsWith('#')) {
        let end = index + 1;
        while (end < line.length && /[A-Za-z_]/.test(line[end] ?? '')) end += 1;
        push(line.slice(index, end), 'pre');
        index = end;
        continue;
      }

      const char = line[index] ?? '';

      if (char === '"') {
        let end = index + 1;
        while (end < line.length && line[end] !== '"') {
          if (line[end] === '\\') end += 1;
          end += 1;
        }
        push(line.slice(index, Math.min(end + 1, line.length)), 'str');
        index = end + 1;
        continue;
      }

      if (DIGIT.test(char)) {
        let end = index;
        while (end < line.length && /[0-9A-Fa-fxX.]/.test(line[end] ?? '')) end += 1;
        push(line.slice(index, end), 'num');
        index = end;
        continue;
      }

      if (IDENT_START.test(char)) {
        let end = index;
        while (end < line.length && IDENT_PART.test(line[end] ?? '')) end += 1;
        const word = line.slice(index, end);
        let lookahead = end;
        while (lookahead < line.length && line[lookahead] === ' ') lookahead += 1;
        const isCall = line[lookahead] === '(';
        if (BUILTINS.has(word) && isCall) push(word, 'fn');
        else if (isCall) push(word, 'fn');
        else if (KEYWORDS.has(word)) push(word, 'kw');
        else if (TYPES.has(word)) push(word, 'type');
        else push(word, 'txt');
        index = end;
        continue;
      }

      push(char, 'txt');
      index += 1;
    }

    result.push(tokens);
  }

  return result;
}
